# vim: set ft=make:
#
AR ?= ar
MPICC ?= mpic++
MPICXX ?= mpic++
LOW_PRECISION ?= double

OPTIMIZE ?= -O2 -g -fopenmp -Wall
#Explicitly set C++ standard
OPTIMIZE += -std=gnu++20
BOOST_INCL ?=
BOOST_LIBS ?=

ifneq ($(findstring -DUSE_CFITSIO, $(OPT)),)
    # If found, set FITSIO_INCL with the cfitsio flags
    FITSIO_INCL ?= $(shell pkg-config --cflags cfitsio)
    FITSIO_LIBS ?= $(shell pkg-config --libs cfitsio)
endif

ifneq ($(findstring -DUSE_CUDA, $(OPT)),)
    CUDA_INCL ?= $(shell pkg-config --cflags cudart)
    CUDA_LIBS ?= $(shell pkg-config --libs cudart)
    NVCC ?= nvcc
    NVOPTIMIZE ?= -O3 -g
endif

OPTIONS = $(OPTIMIZE) $(OPT)
#nvcc needs the location of mpi.h, although no MPI calls are made
MPI_INCL = $(shell pkg-config --cflags ompi-c)
NVOPTIONS = -std=c++20 $(NVOPTIMIZE) $(OPT) $(MPI_INCL)
GADGET_TESTDATA_ROOT = $(CURDIR)/../

CFLAGS = $(OPTIONS) $(BOOST_INCL) $(FITSIO_INCL) $(CUDA_INCL)
CFLAGS += -I../depends/include
CFLAGS += -I../
CFLAGS += "-DLOW_PRECISION=$(LOW_PRECISION)"
#For tests
TCFLAGS = $(CFLAGS) -DGADGET_TESTDATA_ROOT=\"$(GADGET_TESTDATA_ROOT)\"

TBB_LIBS := $(shell echo "int main(void){return 0;}" | $(MPICC) -x c++ - -ltbb -o /dev/null 2>/dev/null && echo "-ltbb")
$(if $(TBB_LIBS),,$(warning TBB not found: building without TBB support))
BUNDLEDLIBS = -lbigfile-mpi -lbigfile -lpfft_omp -lfftw3_mpi -lfftw3_omp -lfftw3 $(TBB_LIBS)
LIBS  = -lm  $(BOOST_LIBS) $(FITSIO_LIBS) $(CUDA_LIBS)
LIBS += -L../depends/lib $(BUNDLEDLIBS)
V ?= 0

.objs/%.o: %.cpp Makefile $(CONFIG)
	@cmd="$(MPICXX) -MMD -c -o $@ $(CFLAGS) $<"; \
	if test "x$(V)" = "x1" ; then echo $$cmd; fi; \
	mkdir -p `dirname $@`; \
	echo Compiling $<; $$cmd

.objs/%.o: %.c Makefile $(CONFIG)
	@cmd="$(MPICC) -MMD -c -o $@ $(CFLAGS) $<"; \
	if test "x$(V)" = "x1" ; then echo $$cmd; fi; \
	mkdir -p `dirname $@`; \
	echo Compiling $<; $$cmd

ifneq ($(findstring -DUSE_CUDA, $(OPT)),)
# Rule to compile .cu files (using nvcc)
.objs/%.o: %.cu Makefile $(CONFIG)
	@cmd="$(NVCC) -MMD -c -o $@ $(NVOPTIONS) -I../depends/include $<"; \
	if test "x$(V)" = "x1" ; then echo $$cmd; fi; \
	mkdir -p `dirname $@`; \
	echo Compiling $<; $$cmd
endif
